# tests.yml

name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a Node
      - name: Runs a Node
        uses: actions/setup-node@v1
        with:
          node-version: 9.5

      # Install and test
      - name: Install and run Ganache
        run: |
          npm install
          npm run ganache

      # Runs a second Node
      - name: Runs a Node
        uses: actions/setup-node@v1
        with:
          node-version: 9.5

      # Install and test
      - name: Build And Deploy
        run: |
          npm run test   